### ISSUE TITLE
Xcode 11 issue

### ISSUE THREAD

**Issue by gilroykilroy** [ReactiveCocoa/ReactiveSwift#755]
Attempting to build with Xcode 11 Beta 7 gives:

/App/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/ReactiveSwift/Sources/Signal.swift:1851:71: error: will never be executed
                                lifetime += action(index, strategy) { observer.send($0.map { _ in fatalError() }) }
                                                                                                  ^
/App/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/ReactiveSwift/Sources/Signal.swift:1851:64: note: '_' is uninhabited, so this function body can never be executed
                                lifetime += action(index, strategy) { observer.send($0.map { _ in fatalError() }) }

**Comment by AQ-TeppeiKikuchi** [comment]
It happened to me too.
please...

**Comment by ikesyo** [comment]
Already resolved by #739. Please update to [6.1.0](https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/6.1.0).

**Comment by gilroykilroy** [comment]
Not for me. Carthage is using:

*** Checking out ReactiveCocoa at "10.0.0"
*** Checking out ReactiveSwift at "6.1.0"

and I still see the error. I made sure I deleted all the caches and deriveddata.

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /App/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa.xcworkspace -scheme ReactiveCocoa-iOS -configuration Release -derivedDataPath ~/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11M392r/ReactiveCocoa/10.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/k3/_596nmws0vd0067hkd1pv7vc0000gn/T/ReactiveCocoa SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /App/Carthage/Checkouts/ReactiveCocoa)

**Comment by gilroykilroy** [comment]
It looks like ReactiveCocoa 10.0.0 is using ReactiveSwift 6.0 which is causing the problem.
